### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by james-hu** [hhandoko/cassandra-migration#14]
## Expected Behaviour

_Should be able to connect to Cassandra_

Please read on. This is not a naive issue caused by networking problem.

I have a Cassandra 3.0.8 docker image running locally. I can connect to it from other tools. I can also connect to it from the code using just Datastax Cassandra driver. cassandra-migration should be able to connect to as well.

<hr>
## Actual Behaviour

_java.net.ConnectException: Connection refused: /127.0.0.1:9402_

Please read on. This is not a naive issue caused by networking problem.

Please see the code below:

``` java
    @Override
    public void afterPropertiesSet() throws Exception {
        cluster = createCluster(servers);
        session = cluster.connect(keySpace);

        KeyspaceConfiguration keyspaceConfig = new KeyspaceConfiguration();
        keyspaceConfig.setName(keySpace);

        keyspaceConfig.getClusterConfig().setContactpoints(Arrays.stream(servers).map(s->StringUtils.split(s, ": ")[0]).toArray(String[]::new));
        keyspaceConfig.getClusterConfig().setPort(Arrays.stream(servers).map(addr-> {
            String[] addrAndPort = StringUtils.split(addr, ": ");
            return addrAndPort.length >= 2 ? Integer.valueOf(addrAndPort[1]) : null;
        }).filter(p->p != null).findAny().orElse(9402));

        CassandraMigration cm = new CassandraMigration();
        cm.setKeyspaceConfig(keyspaceConfig);
        cm.migrate();
    }

    private Cluster createCluster(String[] servers) {
        QueryOptions options = new QueryOptions()
                .setConsistencyLevel(ConsistencyLevel.LOCAL_QUORUM)
                .setSerialConsistencyLevel(ConsistencyLevel.LOCAL_SERIAL);

        Cluster.Builder builder = Cluster.builder()
                .withQueryOptions(options)
                .withClusterName(this.getClass().getName())
                .withTimestampGenerator(new AtomicMonotonicTimestampGenerator())
                //.withCompression(ProtocolOptions.Compression.LZ4)
                ;

        List<InetSocketAddress> contactPointsWithPorts = new ArrayList<>();
        for (String addr: servers){
            String[] addrAndPort = StringUtils.split(addr, ": ");
            if (addrAndPort.length == 1){
                builder.addContactPoint(addrAndPort[0]);
            }else if (addrAndPort.length >= 2){
                contactPointsWithPorts.add(InetSocketAddress.createUnresolved(addrAndPort[0], Integer.parseInt(addrAndPort[1])));
            }
        }
        builder.addContactPointsWithPorts(contactPointsWithPorts);

        builder.withLoadBalancingPolicy(new TokenAwarePolicy(
            DCAwareRoundRobinPolicy.builder().build()));

        Cluster cluster = builder.build();
        cluster.getConfiguration().getCodecRegistry()
                //.register(Codecs.scanCodecs())
                .register(InstantCodec.instance)
                .register(LocalDateCodec.instance);


        return cluster;
    }
```

While my own code (`cluster = createCluster(servers); session = cluster.connect(keySpace);`) can connect to Cassandra without any problem, cassandra-migration (`cm.migrate();`) fails. 

Below is the log / error stack:

```
09:53:44.343 [main] INFO  c.b.c.m.internal.util.VersionPrinter - Cassandra Migration 0.9-SNAPSHOT
09:53:44.343 [main] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.USE_NATIVE_CLOCK is undefined, using default value true
09:53:44.343 [main] INFO  c.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
09:53:44.344 [main] DEBUG com.datastax.driver.core.Cluster - Starting new cluster with contact points [/127.0.0.1:9402]
09:53:44.347 [main] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9402] preparing to open 1 new connections, total = 1
09:53:44.349 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9402-1, inFlight=0, closed=false] Error connecting to /127.0.0.1:9402 (Connection refused: /127.0.0.1:9402)
09:53:44.350 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - Defuncting Connection[/127.0.0.1:9402-1, inFlight=0, closed=false] because: [/127.0.0.1:9402] Cannot connect
09:53:44.350 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9402] preventing new connections for the next 1000 ms
09:53:44.351 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Host.STATES - [/127.0.0.1:9402] Connection[/127.0.0.1:9402-1, inFlight=0, closed=false] failed, remaining = 0
09:53:44.351 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/127.0.0.1:9402-1, inFlight=0, closed=true] closing connection
09:53:44.354 [main] DEBUG c.d.driver.core.ControlConnection - [Control connection] error on /127.0.0.1:9402 connection, no more host to try
com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9402] Cannot connect
    at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:158)
    at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:141)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:518)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:511)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:490)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:431)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
    at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:126)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:276)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:9402
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
    ... 6 common frames omitted
09:53:44.355 [main] DEBUG com.datastax.driver.core.Cluster - Shutting down

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9402 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9402] Cannot connect))

    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1454)
    at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:403)
    at com.builtamont.cassandra.migration.CassandraMigration.execute$cassandra_migration(CassandraMigration.kt:242)
    at com.builtamont.cassandra.migration.CassandraMigration.migrate(CassandraMigration.kt:122)
    at ****************.afterPropertiesSet(Database.java:64)
    at *************.DatabaseIntegrationTest.testMigration(DatabaseIntegrationTest.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

I tried the below but the problem is always the same:
- Alter the execution order of my connection establishment code and cassandra-migration code
- Remove my connection establishment code
- In debug mode of the IDE, manually set a cluster name for cassandra-migration code
- Change ['127.0.0.1'] to ['localhost']

Finally using this code solved the problem:

``` java
    @Override
    public void afterPropertiesSet() throws Exception {
        cluster = createCluster(servers);
        session = cluster.connect(keySpace);

        KeyspaceConfiguration keyspaceConfig = new KeyspaceConfiguration();
        keyspaceConfig.setName(keySpace);
        CassandraMigration cm = new CassandraMigration();
        cm.setKeyspaceConfig(keyspaceConfig);
        cm.migrate(session);
    }
```

<hr>
## Steps to Reproduce
- Cassandra version 3.0.8 docker image running locally
- Datastax driver 3.1.0
- Use 'com.builtamont:cassandra-migration:0.9-SNAPSHOT'
- Use the Java code above

**Comment by hhandoko** [comment]
Hi @james-hu , is it possible to provide your `Dockerfile` as well?

**Comment by james-hu** [comment]
It's just the official one, unmodified (dowloaded from https://hub.docker.com/_/cassandra/). This problem is actually very weird. I debugged into the code but couldn't see anything suspicious. Haven't tried with different versions though.

**Comment by hhandoko** [comment]
Thanks @james-hu . I'll see if I can reproduce this problem with Docker.

**Comment by hhandoko** [comment]
Hi @james-hu , sorry I've put this issue lower in the priority list for now. I'm focusing my effort to finish some tasks on integration tests to allow an `RC1` release.

**Comment by hhandoko** [comment]
Hi @james-hu , I might need your help to bring up the Docker image so I can try to reproduce the problem.

Here's what I've done so far:

1. `docker-machine create --driver virtualbox cassandra-migration`
1. `docker-machine env cassandra-migration`
1. `eval $(docker-machine env cassandra-migration)`
1. `docker run cassandra:3.0.8`

At this stage, the Docker machine is running but I was unable to connect to it via DataStax DevCenter. Did I miss a step somewhere or do I need to perform additional configuration?

**Comment by james-hu** [comment]
Hi! Thanks for getting back to this. I am not familiar with docker-machine. Last time I tried it was on a Mac with just docker. I already left that company so I lost that setup. Probably you can try using "-p 9402:9402"?

**Comment by hhandoko** [comment]
Thanks @james-hu, I'll give it a go.

**Comment by jcam3ron** [comment]
@james-hu your error log shows you're connecting to port 9402. 

The default C* client port is 9042 - this is probably why the default configuration is succeeding but it fails when you manually set the port (I'm assuming you haven't port-forwarded your docker container's port 9042 to 9402 but are passing it straight through to the host)

**Comment by hhandoko** [comment]
Hi @james-hu , are you still interested in this issue? Otherwise I'll close this within the next seven days.

**Comment by james-hu** [comment]
I am sorry for the late reply. And thank you for looking into it. @jcam3ron I am sure it was not about the port mapping because I could connect to the cluster through other tools. @hhandoko No problem about closing it down.  I left that company and I am not using Cassandra in my current project.

**Comment by hhandoko** [comment]
Thanks @james-hu 👍

**Comment by jcam3ron** [comment]
@james-hu Your initial block of code shows you explicitly configuring port 9402, but the code snipped you provide at the end of your description which you said solved the problem will use the default port (9042) to connect to Cassandra. 

If that final block of code ran successfully then I think it is fairly likely that you were specifying the wrong port in your initial code.

**Comment by james-hu** [comment]
@jcam3ron @hhandoko  Ah... Now I get the point. I think you are correct. According to the code and log I quoted in the initial report, I used port number 9402 rather than 9042 in the code. That must have been the reason! What a stupid mistake :-<  :-D

**Comment by hhandoko** [comment]
@james-hu happens to the best of us 😄

**Comment by james-hu** [comment]
@hhandoko That's jcam3ron

**Comment by jcam3ron** [comment]
no worries, I've definitely had my share of mistakes like this! They are always the most frustrating cos you just aren't expecting them :)
