### ISSUE TITLE
parameter installedBy should be optional

### ISSUE THREAD

**Issue by felixgao** [hhandoko/cassandra-migration#19]
according to the README the username is optional. so installedBy should be nullable but

```
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.builtamont.cassandra.migration.internal.metadatatable.AppliedMigration.<init>, parameter installedBy
        at com.builtamont.cassandra.migration.internal.metadatatable.AppliedMigration.<init>(AppliedMigration.kt)
        at com.builtamont.cassandra.migration.internal.dbsupport.SchemaVersionDAO.findAppliedMigrations(SchemaVersionDAO.java:238)
        at com.builtamont.cassandra.migration.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.kt:58)
        at com.builtamont.cassandra.migration.internal.command.Migrate.run(Migrate.kt:71)
        at com.builtamont.cassandra.migration.CassandraMigration$migrateAction$1.execute(CassandraMigration.kt:357)
        at com.builtamont.cassandra.migration.CassandraMigration$migrateAction$1.execute(CassandraMigration.kt:342)
        at com.builtamont.cassandra.migration.CassandraMigration.execute$cassandra_migration(CassandraMigration.kt:265)
        at com.builtamont.cassandra.migration.CassandraMigration.migrate(CassandraMigration.kt:131)
        at com.builtamont.cassandra.migration.CommandLine.main(CommandLine.kt:73)
```

**Comment by felixgao** [comment]
it seems I have an older schema, destroyed the keyspace and recreate made this error go away.
